const GET_ATICLES_SAGA = 'GET_ATICLES_SAGA'
const GET_ATICLES_SUCCESS = 'GET_ATICLES_SUCCESS'
const GET_ATICLES_FAILURE = 'GET_ATICLES_FAILURE'

export const actionType = {
	GET_ATICLES_SAGA,
	GET_ATICLES_SUCCESS,
	GET_ATICLES_FAILURE,
}
