const GET_ATICLES = 'GET_ATICLES'
const GET_ATICLES_SUCCESS = 'GET_ATICLES_SUCCESS'
const GET_ATICLES_FAILURE = 'GET_ATICLES_FAILURE'

export const actionType = {
	GET_ATICLES,
	GET_ATICLES_SUCCESS,
	GET_ATICLES_FAILURE,
}
